package inflation

object InflationInsertGenerator {

    fun generate(data: List<Double>, inflationType: String, startingYear: Int)
            : String {

        val result = StringBuilder()

        result.appendln("-- Generated by ${this.javaClass.simpleName} --")
        result.appendln()

        result.appendln("DELETE from inflation_rate WHERE type = '$inflationType';")
        result.appendln("INSERT INTO inflation_rate (month, year, type, value_percent) VALUES")

        var currentYear = startingYear
        var currentMonth = 1

        print("\n")

        data.forEachIndexed { index, value ->

            result.append("($currentMonth, $currentYear, '$inflationType',$value)")

            if (data.lastIndex != index) {
                result.append(",")
            } else {
                result.append(";")
            }

            result.append("\n")

            currentMonth++

            if (currentMonth >= 13) {
                currentMonth = 1
                currentYear++
            }

        }

        result.appendln()
        result.appendln("-- Generated by ${this.javaClass.simpleName} --")
        result.appendln()

        println(result)

        return result.toString()
    }

}