runtime: java11

instance_class: B2

#automatic_scaling:
#  max_instances: 1

basic_scaling:
  max_instances: 1
  idle_timeout: 30m

env_variables:
  SPRING_PROFILES_ACTIVE: "prod"

handlers:
- url: .*
  secure: always
  script: auto