name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup jdk
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
      - name: build
        run: ./mvnw clean && ./mvnw compile
