name: CI

on: [push]

jobs:
  test:
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: setup jdk
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11

      - name: checkout project's git repository
        uses: actions/checkout@v2.0.0

      - name: shutdown ubuntu's mysql - in case its already running - advised by mysql-action
        run: sudo service mysql stop

      - name: setup mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: 'password'
          mysql database: 'test_economy'
          mysql user: 'root'
          mysql password: 'password'

      - name: add rights to mvnw
        run: chmod +x ./mvnw

      - name: unit test
        run: ./mvnw clean && ./mvnw test

  test-and-deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: setup jdk
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 11

      - name: checkout project's git repository
        uses: actions/checkout@v2.0.0

      - name: set database name
        uses: christian-draeger/write-properties@1.0.0
        with:
          path: './src/main/resources/application-prod.properties'
          property: 'spring.cloud.gcp.sql.database-name'
          value: ${{secrets.database_name}}

      - name: set instance connection
        uses: christian-draeger/write-properties@1.0.0
        with:
          path: './src/main/resources/application-prod.properties'
          property: 'spring.cloud.gcp.sql.instance-connection-name'
          value: ${{secrets.database_instance_connection_name}}

      - name: set database user
        uses: christian-draeger/write-properties@1.0.0
        with:
          path: './src/main/resources/application-prod.properties'
          property: 'spring.datasource.username'
          value: ${{secrets.database_user}}

      - name: set database password
        uses: christian-draeger/write-properties@1.0.0
        with:
          path: './src/main/resources/application-prod.properties'
          property: 'spring.datasource.password'
          value: ${{secrets.database_password}}

      - name: set default user name
        uses: christian-draeger/write-properties@1.0.0
        with:
          path: './src/main/resources/application-prod.properties'
          property: 'spring.security.user.name'
          value: ${{secrets.security_user_name}}

      - name: set default user password
        uses: christian-draeger/write-properties@1.0.0
        with:
          path: './src/main/resources/application-prod.properties'
          property: 'spring.security.user.password'
          value: ${{secrets.security_user_password}}

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_email: ${{ secrets.google_application_service_account_email }}
          service_account_key: ${{ secrets.google_application_service_key }}
      - run: gcloud config set project ${{secrets.google_cloud_project_id}}

      - name: shutdown ubuntu's mysql - in case its already running - advised by mysql-action
        run: sudo service mysql stop

      - name: setup mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: 'password'
          mysql database: 'test_economy'
          mysql user: 'root'
          mysql password: 'password'

      - name: add rights to mvnw
        run: chmod +x mvnw

      - name: package
        run: ./mvnw clean package

      - name: deploy
        run: ./mvnw appengine:deploy
